name: Superstar
favicon: null
layout_spectrum: 0.11597
typography_spectrum: 0.08333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#051e23'
    - '#00a0bc'
    - '#00ffff'
    - '#f7ffff'
    - '#7c8999'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 1
purpose:
  - name: follow
    item: 9a0eed1e-2e15-4a96-8110-10393d5cd06f
    url: null
