name: Superstar
favicon: null
layout_spectrum: 0.99097
typography_spectrum: 0.25694
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#051e23'
    - '#00a0bc'
    - '#00ffff'
    - '#f7ffff'
    - '#7c8999'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 1
purpose:
  - name: follow
    item: f9f9ab00-2417-4cb1-b19d-80f9851c24a1
    url: null
